apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  labels:
    app: greeting
spec:
  replicas: 4
  minReadySeconds: 15
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting-service
          image: alxlys/docker-test:2.0
          ports:
            - containerPort: 8080
#          resources:
#            limits:
#              memory: "128Mi"
#              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /greeting
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /greeting
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 1