apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  labels:
    app: greeting
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting-service
          image: alxlys/docker-test:2.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-config-vol
              mountPath: /etc/config
#          Individual env prop from file
          env:
            - name: ENEMIES
              valueFrom:
                configMapKeyRef:
                  name: app-settings
                  key: enemies
#          All env props from file
          envFrom:
            - configMapRef:
                name: app-settings
          livenessProbe:
            httpGet:
              path: /greeting
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /greeting
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 1
#      Java app is not modified to display values, but can be checkec with "kubectl exec <pod> -ti sh"
      volumes:
        - name: app-config-vol
          configMap:
            name: app-settings